name: movie_night
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  lottie: ^1.0.1
  flutter_zoom_drawer: ^3.1.1
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  http: ^1.1.0
  url_launcher: ^6.1.12
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  awesome_dialog: ^3.1.0
  cloud_firestore: ^4.9.0
  flutter_launcher_icons: ^0.13.1
  internet_connection_checker: ^1.0.0+1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/Logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
